name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Install dependencies
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libffi-dev libssl-dev libzbar-dev python3-venv openjdk-8-jdk wget unzip
        python3 -m pip install --upgrade pip setuptools wheel
        pip install buildozer cython

    # Install Android SDK and Tools
    - name: Install Android SDK and Tools
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-9123335_latest.zip -O cmdline-tools.zip
        mkdir -p $HOME/android-sdk/cmdline-tools/latest
        unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools/latest
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
        echo "PATH=$PATH" >> $GITHUB_ENV
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "platforms;android-31" "build-tools;31.0.0"

    # Build APK
    - name: Build APK
      run: |
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        buildozer android debug
        ls -al ./bin

    # Upload APK as artifact
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: bin/*.apk
